# See https://github.com/crate-ci/typos/blob/master/docs/reference.md to configure typos
[default.extend-words]
Formated = "Formated"   # TODO: correct it later
Formating = "Formating" # TODO: correct it later
[files]
extend-exclude = ["vendor/*"]
